import type { Entry } from "./types";
import { FLOW_GIFS, STUDIO_URL } from "./tools";
import { SAMPLE_ENTRY_EN } from "./sample.en";

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

const BASE_SAMPLE_ENTRIES: Entry[] = [
  /* =============================== 공지사항 =============================== */
  {
    id: "notice-kbs",
    type: "notice",
    title: "XCONDA, KBS Production 검증 완료 안내",
    summary: "인과관계 기반(Causality-Driven) AI 스토리보드가 KBS Production 제작 워크플로우 검증을 통과했습니다.",
    category: "공지",
    date: daysAgo(1),
    author: "XCONDA 팀",
    tags: ["KBS", "Verified"],
    pinned: true,
    important: true,
    blocks: [
      { type: "p", text: "안녕하세요, XCONDA 팀입니다. XCONDA ADP가 KBS Production의 실제 제작 워크플로우 검증을 완료했음을 알려드립니다." },
      { type: "h2", text: "검증 항목" },
      { type: "ul", items: ["9컷 스토리보드의 컷 간 연속성(감정선·소품·의상)", "캐릭터 얼굴 일관성", "피드백 반영 후 맥락 유지"] },
      { type: "callout", icon: "🎬", text: "앞으로도 현업 프로덕션 기준에 맞춘 기능을 빠르게 업데이트하겠습니다." },
    ],
  },
  {
    id: "notice-maint",
    type: "notice",
    title: "[점검] 서버 안정화 정기 점검 안내",
    summary: "보다 안정적인 생성 환경을 위해 정기 점검이 진행됩니다. 점검 중에는 일부 툴 사용이 제한됩니다.",
    category: "점검",
    date: daysAgo(2),
    tags: ["Maintenance"],
    important: true,
    blocks: [
      { type: "callout", icon: "🛠", text: "점검 시간 동안 생성 요청이 일시적으로 대기열에 머무를 수 있습니다." },
      { type: "h3", text: "영향 범위" },
      { type: "ul", items: ["Director's Cut · Art Director Pro 생성", "크레딧 결제는 정상 이용 가능"] },
      { type: "p", text: "점검 중 차감된 크레딧은 점검 종료 후 자동 복구됩니다." },
    ],
  },
  {
    id: "notice-sub",
    type: "notice",
    title: "구독 플랜 출시 예정 안내",
    summary: "현재 크레딧 팩은 1회 결제 방식입니다. 월 구독 플랜을 준비 중이며, 출시 시 공지로 안내드립니다.",
    category: "정책",
    date: daysAgo(5),
    tags: ["Credits", "Plan"],
    blocks: [
      { type: "p", text: "현재 모든 크레딧 팩(Starter · Pro · Master)은 1회 결제 방식으로 제공됩니다." },
      { type: "p", text: "월 구독 플랜을 준비하고 있으며, 기존 보유 크레딧은 구독 전환 후에도 그대로 사용하실 수 있습니다." },
    ],
  },
  {
    id: "notice-event",
    type: "notice",
    title: "Ad Storyboard 템플릿 챌린지 이벤트",
    summary: "Ad Storyboard 템플릿으로 만든 9컷 스토리보드를 공유해 주세요. 우수작에 크레딧을 드립니다.",
    category: "이벤트",
    date: daysAgo(9),
    tags: ["Event", "Director's Cut"],
    blocks: [
      { type: "ol", items: ["Director's Cut에서 Ad Storyboard 템플릿으로 스토리보드 제작", "SNS에 #XCONDA 해시태그와 함께 공유", "이벤트 페이지에 링크 제출"] },
      { type: "link", href: `${STUDIO_URL}/studio/directors-cut`, caption: "Ad Storyboard 템플릿으로 시작하기" },
    ],
  },
  {
    id: "notice-policy",
    type: "notice",
    title: "Face Swap 이용 정책 업데이트",
    summary: "타인의 초상권 보호를 위해 Face Swap 이용 가이드라인이 업데이트되었습니다.",
    category: "정책",
    date: daysAgo(16),
    tags: ["Policy", "Face Swap"],
    blocks: [{ type: "p", text: "본인 또는 사용 동의를 받은 인물의 얼굴만 사용해 주세요. 정책 위반 시 이용이 제한될 수 있습니다." }],
  },
  {
    id: "notice-welcome",
    type: "notice",
    title: "XCONDA허브 오픈",
    summary: "공지사항, 뉴스, 툴 사용법, 블로그, Q&A를 한곳에서 확인할 수 있는 XCONDA허브를 오픈했습니다.",
    category: "공지",
    date: daysAgo(24),
    tags: ["Guide"],
    blocks: [{ type: "p", text: "XCONDA허브의 모든 콘텐츠는 Notion과 실시간으로 연동되어, 새로운 소식을 가장 빠르게 전해드립니다." }],
  },

  /* ========================= 뉴스 (타 SNS 정보) ========================= */
  {
    id: "news-240",
    type: "news",
    title: "[YouTube] Turn (턴) 360 공간 큐브맵 & 마스크 편집 업데이트",
    summary: "사진 1장으로 6면 큐브맵을 생성해 공간을 고정하고, 마스크 영역으로 오브젝트를 추가·제거하는 방법을 영상으로 공개했습니다.",
    category: "YouTube",
    version: "v2.4.0",
    date: daysAgo(1),
    tags: ["Turn", "YouTube"],
    changes: [
      { kind: "New", text: "사진 1장 → 6면 큐브맵 배경 고정 (컷 전환 시 공간 일관성 유지)" },
      { kind: "New", text: "마스크 영역 + 빈 프롬프트 → 오브젝트 자동 제거" },
      { kind: "Improved", text: "3D 시점 Freeze Frame 및 Production 렌더 품질 향상" },
    ],
    blocks: [
      { type: "p", text: "XCONDA 공식 YouTube 채널에 Turn 360 공간 고정 워크플로우 영상이 올라왔습니다. 큐브맵 생성부터 마스크 편집까지 6분 분량으로 담았습니다." },
      { type: "callout", icon: "🎬", text: "영상 링크는 Notion 글의 Link(URL) 속성에 넣으면 상세 모달의 버튼으로 노출됩니다." },
    ],
  },
  {
    id: "news-230",
    type: "news",
    title: "[Instagram] FlexBoard 컷 단위 선택 재생성 릴스",
    summary: "9컷 그리드에서 마음에 들지 않는 컷만 골라 다시 만드는 선택 재생성(Selective Regeneration) 과정을 짧은 영상으로 공유합니다.",
    category: "Instagram",
    version: "v2.3.0",
    date: daysAgo(6),
    tags: ["FlexBoard", "Instagram"],
    changes: [
      { kind: "New", text: "컷별 프롬프트 수정 및 횟수 제한 없는 개별 재생성" },
      { kind: "New", text: "Claude 프롬프트 스킬(xconda-new-prompt) 및 Seedance 2.5 연동 지원" },
      { kind: "Fixed", text: "9컷 생성 시 순서 및 감정선 맥락 유지 강화" },
    ],
    blocks: [
      { type: "p", text: "인스타그램 릴로 공개한 FlexBoard 선택 재생성 데모입니다. 전체 보드를 다시 만들지 않고 한 컷만 고치는 흐름을 확인할 수 있습니다." },
    ],
  },
  {
    id: "news-220",
    type: "news",
    title: "[X] Art Director Pro 연속성 메모리 출시",
    summary: "캐릭터의 감정, 부상, 소품 상태와 이전 프롬프트가 모든 씬에 걸쳐 기억됩니다.",
    category: "X",
    version: "v2.2.0",
    date: daysAgo(13),
    tags: ["Art Director Pro", "X"],
    cover: FLOW_GIFS.continuity,
    changes: [
      { kind: "New", text: "감정 · 부상 · 소품 상태 연속성 메모리" },
      { kind: "Improved", text: "Detect Face 인식 정확도 향상" },
      { kind: "Improved", text: "재생성 시 이전 컷 톤 유지" },
    ],
    blocks: [
      { type: "p", text: "X(트위터)에 먼저 알린 연속성 메모리 출시 소식입니다. 컷이 바뀔 때마다 캐릭터가 초기화되던 문제가 해결되었습니다." },
    ],
  },
  {
    id: "news-210",
    type: "news",
    title: "[LinkedIn] 신규 툴 3종: CineGrade AI · ClothSwap · YouTube Ref",
    summary: "색보정 이식, 의상 교체, 유튜브 링크 기반 9씬 스토리보드 툴이 추가되었습니다.",
    category: "LinkedIn",
    version: "v2.1.0",
    date: daysAgo(21),
    tags: ["Tools", "LinkedIn"],
    changes: [
      { kind: "New", text: "CineGrade AI — 영화 스틸 컬러 그레이딩 이식" },
      { kind: "New", text: "ClothSwap — 브러시 + 참조 이미지 의상 교체" },
      { kind: "New", text: "YouTube Ref — 영상 링크로 9씬 스토리보드" },
    ],
    blocks: [
      { type: "p", text: "파트너사와 제작사를 대상으로 LinkedIn에 공유한 신규 툴 3종 안내입니다." },
    ],
  },
  {
    id: "news-200",
    type: "news",
    title: "[Notion] 올인원 모델 워크스페이스 릴리스 노트",
    summary: "모든 AI 모델을 하나의 워크스페이스에서. 모델을 바꿔도 세부 파라미터가 일관되게 유지됩니다.",
    category: "Notion",
    version: "v2.0.0",
    date: daysAgo(34),
    tags: ["Models", "Notion"],
    cover: FLOW_GIFS.models,
    changes: [
      { kind: "New", text: "Kling 3.0 영상 모델 · Grok Imagine 이미지 모델 지원" },
      { kind: "Improved", text: "모델 전환 시 파라미터 유지" },
      { kind: "New", text: "Upscaler 6K 지원" },
    ],
    blocks: [
      { type: "p", text: "XCONDA_NEWs 노션 데이터베이스에 기록된 v2.0.0 릴리스 노트입니다. 이 페이지의 모든 콘텐츠와 동일한 원본입니다." },
    ],
  },

  /* ================================ 가이드 ================================ */
  {
    id: "guide-start",
    type: "guide",
    title: "처음 시작하기: Turn에서 FlexBoard까지 5분 완성",
    summary: "Turn으로 공간을 고정하고 FlexBoard로 9컷 스토리보드를 만드는 핵심 워크플로우를 안내합니다.",
    category: "시작하기",
    date: daysAgo(3),
    tags: ["Beginner", "Turn", "FlexBoard"],
    order: 1,
    cover: FLOW_GIFS.storyboard,
    blocks: [
      { type: "h2", text: "1. Turn으로 배경/공간 고정하기" },
      { type: "p", text: "사진 한 장을 업로드하여 6면 큐브맵을 만들고 원하는 시점을 Freeze Frame으로 저장합니다. 공간을 먼저 고정해야 컷이 바뀌어도 방이 흔들리지 않습니다." },
      { type: "h2", text: "2. FlexBoard에서 9컷 스토리보드 생성" },
      { type: "ol", items: ["시나리오 작성", "감독 연출 및 아트 스타일 선택", "Generate로 9컷 일괄 생성", "필요한 컷만 개별 재생성(Selective Regeneration)"] },
      { type: "h2", text: "3. 영상화 렌더링" },
      { type: "p", text: "완성된 9컷 보드를 Seedance 2.5 또는 Kling 영상 모델로 전달해 최종 비디오를 제작합니다." },
      { type: "callout", icon: "💡", text: "Turn → FlexBoard → Blocking Board → Seedance 2.5가 XCONDA의 정식 프로덕션 파이프라인입니다." },
    ],
  },
  {
    id: "guide-prompt",
    type: "guide",
    title: "좋은 시나리오 작성법",
    summary: "인물 · 장소 · 감정 흐름 · 카메라를 담으면 9컷의 완성도가 달라집니다.",
    category: "시나리오",
    date: daysAgo(8),
    tags: ["Prompt", "FlexBoard"],
    order: 2,
    blocks: [
      { type: "p", text: "XCONDA는 인과관계 기반 AI입니다. 사건의 원인과 결과가 드러나도록 쓰면 컷 간 흐름이 자연스러워집니다." },
      { type: "h3", text: "체크리스트" },
      { type: "todo", items: [
        { text: "인물의 이름을 명시했나요? (Art Director Pro 연결에 필요)", checked: true },
        { text: "시간 · 장소를 적었나요?", checked: true },
        { text: "감정 변화(시작 → 전환 → 결말)가 있나요?", checked: false },
        { text: "핵심 소품이나 의상을 명시했나요?", checked: false },
      ] },
      { type: "h3", text: "예시" },
      { type: "quote", text: "1998년 서울, 비 오는 밤. 민지는 폐업한 필름 현상소 앞에서 아버지의 낡은 카메라를 발견한다. 망설이다 셔터를 누르는 순간, 거리의 네온이 하나씩 켜진다." },
    ],
  },
  {
    id: "guide-character",
    type: "guide",
    title: "캐릭터 일관성 유지하기",
    summary: "Art Director Pro에서 얼굴 · 의상이 모든 컷에서 유지되도록 설정하는 방법.",
    category: "캐릭터",
    date: daysAgo(12),
    tags: ["Art Director Pro"],
    order: 3,
    tool: "Art Director Pro",
    blocks: [
      { type: "ol", items: ["시나리오에 캐릭터 이름 포함", "얼굴 사진 업로드", "Detect Face → 캐릭터 시트 생성", "생성 및 재생성"] },
      { type: "callout", icon: "⚠️", text: "캐릭터 시트가 없으면 생성을 시작할 수 없습니다." },
    ],
  },

  /* ================================ 블로그 ================================ */
  {
    id: "blog-pipeline",
    type: "blog",
    title: "Turn → FlexBoard → Blocking Board → Seedance 2.5, 9컷 영상 만드는 순서",
    summary: "공간을 먼저 고정하고 컷을 만든 뒤 영상으로 넘기는 XCONDA 정식 프로덕션 파이프라인을 순서대로 정리했습니다.",
    category: "워크플로우",
    date: daysAgo(4),
    author: "XCONDA 프로덕션 팀",
    tags: ["Turn", "FlexBoard", "Pipeline"],
    order: 1,
    cover: FLOW_GIFS.storyboard,
    blocks: [
      { type: "h2", text: "1. 공간 고정 (Turn)" },
      { type: "p", text: "사진 한 장으로 6면 큐브맵을 만들고, 원하는 시점을 Freeze Frame으로 저장합니다. 공간을 먼저 잡아야 컷이 바뀌어도 배경이 흔들리지 않습니다." },
      { type: "h2", text: "2. 컷 생성 (FlexBoard)" },
      { type: "ol", items: ["시나리오 작성", "감독 연출 · 아트 스타일 선택", "Generate로 9컷 일괄 생성", "마음에 안 드는 컷만 선택 재생성"] },
      { type: "h2", text: "3. 동선 연출 (Blocking Board)" },
      { type: "p", text: "인물의 위치와 카메라 동선을 배치해 컷 간의 연결을 설계합니다." },
      { type: "h2", text: "4. 영상화 (Seedance 2.5 · Kling)" },
      { type: "p", text: "완성된 보드를 영상 모델로 넘겨 최종 컷을 렌더링합니다." },
      { type: "callout", icon: "💡", text: "순서를 지키면 재생성 횟수가 줄어 크레딧도 아낄 수 있습니다." },
    ],
  },
  {
    id: "blog-continuity",
    type: "blog",
    title: "컷이 바뀌어도 얼굴이 안 바뀌는 캐릭터 시트 만들기",
    summary: "Art Director Pro의 Detect Face와 이름 연결 규칙만으로 캐릭터 일관성을 확보하는 실전 팁입니다.",
    category: "튜토리얼",
    date: daysAgo(10),
    author: "김하나 PD",
    tags: ["Art Director Pro", "Character"],
    order: 2,
    tool: "Art Director Pro",
    blocks: [
      { type: "p", text: "캐릭터가 컷마다 달라지는 문제의 대부분은 시나리오에 이름이 없거나 캐릭터 시트를 만들지 않아서 발생합니다." },
      { type: "h3", text: "순서" },
      { type: "ol", items: ["시나리오에 캐릭터 이름 명시", "얼굴 사진 업로드", "Detect Face → 캐릭터 시트 생성", "생성 · 재생성"] },
      { type: "callout", icon: "⚠️", text: "캐릭터 시트가 없으면 생성이 시작되지 않습니다." },
    ],
  },
  {
    id: "blog-interview",
    type: "blog",
    title: "KBS Production 검증 후기 — 인과관계 기반 AI가 현장에서 통했던 이유",
    summary: "실제 제작 워크플로우 검증 과정에서 확인한 강점과, 개선이 필요했던 지점을 함께 기록했습니다.",
    category: "인사이트",
    date: daysAgo(18),
    author: "이도현 감독",
    tags: ["KBS", "Causality"],
    order: 3,
    blocks: [
      { type: "p", text: "검증 항목은 컷 간 연속성(감정선 · 소품 · 의상), 캐릭터 얼굴 일관성, 피드백 반영 후 맥락 유지였습니다." },
      { type: "quote", text: "사건의 원인과 결과가 드러나도록 시나리오를 쓰면 컷 간 흐름이 자연스럽게 이어집니다." },
      { type: "h3", text: "개선 과제" },
      { type: "ul", items: ["장문 시나리오의 토큰 분할", "재생성 시 이전 컷 톤 유지"] },
    ],
  },

  /* ================================== Q&A ================================== */
  { id: "faq-1", type: "faq", order: 1, title: "크레딧은 어떻게 충전하나요?", summary: "크레딧 팩(Starter V1 · V2, Pro V1 · V2, Master)을 1회 결제로 구매할 수 있습니다. 구독 플랜은 출시 예정입니다.", category: "크레딧", date: daysAgo(3), tags: [] },
  { id: "faq-2", type: "faq", order: 2, title: "생성에 실패하면 크레딧이 차감되나요?", summary: "시스템 오류로 생성이 실패한 경우 차감된 크레딧은 자동으로 복구됩니다. 복구되지 않았다면 문의해 주세요.", category: "크레딧", date: daysAgo(3), tags: [] },
  { id: "faq-3", type: "faq", order: 3, title: "마음에 안 드는 컷만 다시 만들 수 있나요?", summary: "네. FlexBoard / Director's Cut에서 해당 컷의 프롬프트만 수정해 개별 선택 재생성(Selective Regeneration)할 수 있습니다. 나머지 컷의 맥락은 그대로 유지됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-4", type: "faq", order: 4, title: "캐릭터 얼굴이 컷마다 달라져요.", summary: "Art Director Pro에서 시나리오에 캐릭터 이름을 넣고, 얼굴 사진 업로드 후 Detect Face로 캐릭터 시트를 만들어 주세요. 이름으로 얼굴이 연결됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-5", type: "faq", order: 5, title: "Turn (턴)에서 오브젝트를 지우거나 변경하려면?", summary: "Inpaint 마스크 툴로 영역을 칠하고, Replace with를 비워 둔 채 실행하면 오브젝트가 자동 제거됩니다. 새 프롬프트를 입력하면 해당 오브젝트로 교체됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-6", type: "faq", order: 6, title: "만든 결과물을 상업적으로 사용할 수 있나요?", summary: "이용약관의 범위 내에서 사용 가능합니다. 타인의 초상 · 저작물을 사용하는 경우 반드시 권리자의 동의가 필요합니다.", category: "정책", date: daysAgo(3), tags: [] },
];

export const SAMPLE_ENTRIES: Entry[] = BASE_SAMPLE_ENTRIES.map((entry) => ({
  ...entry,
  translations: SAMPLE_ENTRY_EN[entry.id] ? { en: SAMPLE_ENTRY_EN[entry.id] } : undefined,
}));
