import type { Entry } from "./types";
import { FLOW_GIFS, STUDIO_URL } from "./tools";
import { SAMPLE_ENTRY_EN } from "./sample.en";

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

const BASE_SAMPLE_ENTRIES: Entry[] = [
  /* =============================== 공지사항 =============================== */
  {
    id: "notice-kbs",
    type: "notice",
    title: "XCONDA, KBS Production 검증 완료 안내",
    summary: "인과관계 기반(Causality-Driven) AI 스토리보드가 KBS Production 제작 워크플로우 검증을 통과했습니다.",
    category: "공지",
    date: daysAgo(1),
    tags: ["KBS", "Verified"],
    pinned: true,
    important: true,
    blocks: [
      { type: "p", text: "안녕하세요, XCONDA 팀입니다. XCONDA ADP가 KBS Production의 실제 제작 워크플로우 검증을 완료했음을 알려드립니다." },
      { type: "h2", text: "검증 항목" },
      { type: "ul", items: ["9컷 스토리보드의 컷 간 연속성(감정선·소품·의상)", "캐릭터 얼굴 일관성", "피드백 반영 후 맥락 유지"] },
      { type: "callout", icon: "🎬", text: "앞으로도 현업 프로덕션 기준에 맞춘 기능을 빠르게 업데이트하겠습니다." },
    ],
  },
  {
    id: "notice-maint",
    type: "notice",
    title: "[점검] 서버 안정화 정기 점검 안내",
    summary: "보다 안정적인 생성 환경을 위해 정기 점검이 진행됩니다. 점검 중에는 일부 툴 사용이 제한됩니다.",
    category: "점검",
    date: daysAgo(2),
    tags: ["Maintenance"],
    important: true,
    blocks: [
      { type: "callout", icon: "🛠", text: "점검 시간 동안 생성 요청이 일시적으로 대기열에 머무를 수 있습니다." },
      { type: "h3", text: "영향 범위" },
      { type: "ul", items: ["Director's Cut · Art Director Pro 생성", "크레딧 결제는 정상 이용 가능"] },
      { type: "p", text: "점검 중 차감된 크레딧은 점검 종료 후 자동 복구됩니다." },
    ],
  },
  {
    id: "notice-sub",
    type: "notice",
    title: "구독 플랜 출시 예정 안내",
    summary: "현재 크레딧 팩은 1회 결제 방식입니다. 월 구독 플랜을 준비 중이며, 출시 시 공지로 안내드립니다.",
    category: "정책",
    date: daysAgo(5),
    tags: ["Credits", "Plan"],
    blocks: [
      { type: "p", text: "현재 모든 크레딧 팩(Starter · Pro · Master)은 1회 결제 방식으로 제공됩니다." },
      { type: "p", text: "월 구독 플랜을 준비하고 있으며, 기존 보유 크레딧은 구독 전환 후에도 그대로 사용하실 수 있습니다." },
    ],
  },
  {
    id: "notice-event",
    type: "notice",
    title: "Ad Storyboard 템플릿 챌린지 이벤트",
    summary: "Ad Storyboard 템플릿으로 만든 9컷 스토리보드를 공유해 주세요. 우수작에 크레딧을 드립니다.",
    category: "이벤트",
    date: daysAgo(9),
    tags: ["Event", "Director's Cut"],
    blocks: [
      { type: "ol", items: ["Director's Cut에서 Ad Storyboard 템플릿으로 스토리보드 제작", "SNS에 #XCONDA 해시태그와 함께 공유", "이벤트 페이지에 링크 제출"] },
      { type: "link", href: `${STUDIO_URL}/studio/directors-cut`, caption: "Ad Storyboard 템플릿으로 시작하기" },
    ],
  },
  {
    id: "notice-policy",
    type: "notice",
    title: "Face Swap 이용 정책 업데이트",
    summary: "타인의 초상권 보호를 위해 Face Swap 이용 가이드라인이 업데이트되었습니다.",
    category: "정책",
    date: daysAgo(16),
    tags: ["Policy", "Face Swap"],
    blocks: [{ type: "p", text: "본인 또는 사용 동의를 받은 인물의 얼굴만 사용해 주세요. 정책 위반 시 이용이 제한될 수 있습니다." }],
  },
  {
    id: "notice-welcome",
    type: "notice",
    title: "XCONDA 가이드 센터 오픈",
    summary: "공지사항, 업데이트 내역, 툴별 사용법을 한곳에서 확인할 수 있는 가이드 센터를 오픈했습니다.",
    category: "공지",
    date: daysAgo(24),
    tags: ["Guide"],
    blocks: [{ type: "p", text: "가이드 센터의 모든 콘텐츠는 Notion과 실시간으로 연동되어, 새로운 소식을 가장 빠르게 전해드립니다." }],
  },

  /* ============================== 업데이트 ============================== */
  {
    id: "update-240",
    type: "update",
    title: "360 Turn Studio 마스크 자동 지우기",
    summary: "프롬프트를 비우고 마스크를 칠하면 오브젝트가 자동으로 제거됩니다.",
    category: "Release",
    version: "v2.4.0",
    date: daysAgo(1),
    tags: ["360 Turn Studio"],
    cover: FLOW_GIFS.tools,
    changes: [
      { kind: "New", text: "마스크 영역 + 빈 프롬프트 → 오브젝트 자동 제거" },
      { kind: "New", text: "공간 내 캐릭터 선택 및 배치" },
      { kind: "Improved", text: "레퍼런스 이미지 기반 3D 공간 복원 품질 향상" },
    ],
  },
  {
    id: "update-230",
    type: "update",
    title: "Director's Cut 컷 단위 재생성",
    summary: "마음에 들지 않는 컷만 프롬프트를 수정해 개별 재생성할 수 있습니다.",
    category: "Release",
    version: "v2.3.0",
    date: daysAgo(6),
    tags: ["Director's Cut"],
    cover: FLOW_GIFS.storyboard,
    changes: [
      { kind: "New", text: "컷별 프롬프트 편집 및 개별 재생성" },
      { kind: "New", text: "감독 스타일 · 아트 스타일 프리셋 추가" },
      { kind: "Fixed", text: "9컷 생성 시 간헐적으로 순서가 바뀌던 문제" },
    ],
  },
  {
    id: "update-220",
    type: "update",
    title: "Art Director Pro 연속성 메모리",
    summary: "캐릭터의 감정, 부상, 소품 상태와 이전 프롬프트가 모든 씬에 걸쳐 기억됩니다.",
    category: "Release",
    version: "v2.2.0",
    date: daysAgo(13),
    tags: ["Art Director Pro"],
    cover: FLOW_GIFS.continuity,
    changes: [
      { kind: "New", text: "감정 · 부상 · 소품 상태 연속성 메모리" },
      { kind: "Improved", text: "Detect Face 인식 정확도 향상" },
      { kind: "Improved", text: "재생성 시 이전 컷 톤 유지" },
    ],
  },
  {
    id: "update-210",
    type: "update",
    title: "신규 툴 3종: CineGrade AI · ClothSwap · YouTube Ref",
    summary: "색보정 이식, 의상 교체, 유튜브 링크 기반 9씬 스토리보드 툴이 추가되었습니다.",
    category: "Release",
    version: "v2.1.0",
    date: daysAgo(21),
    tags: ["Tools"],
    changes: [
      { kind: "New", text: "CineGrade AI — 영화 스틸 컬러 그레이딩 이식" },
      { kind: "New", text: "ClothSwap — 브러시 + 참조 이미지 의상 교체" },
      { kind: "New", text: "YouTube Ref — 영상 링크로 9씬 스토리보드" },
    ],
  },
  {
    id: "update-200",
    type: "update",
    title: "올인원 모델 워크스페이스",
    summary: "모든 AI 모델을 하나의 워크스페이스에서. 모델을 바꿔도 세부 파라미터가 일관되게 유지됩니다.",
    category: "Release",
    version: "v2.0.0",
    date: daysAgo(34),
    tags: ["Models"],
    cover: FLOW_GIFS.models,
    changes: [
      { kind: "New", text: "Kling 3.0 영상 모델 · Grok Imagine 이미지 모델 지원" },
      { kind: "Improved", text: "모델 전환 시 파라미터 유지" },
      { kind: "New", text: "Upscaler 6K 지원" },
    ],
  },

  /* ================================ 가이드 ================================ */
  {
    id: "guide-start",
    type: "guide",
    title: "처음 시작하기: 5분 만에 첫 스토리보드",
    summary: "가입부터 첫 9컷 스토리보드 완성까지, 가장 빠른 경로를 안내합니다.",
    category: "시작하기",
    date: daysAgo(3),
    tags: ["Beginner"],
    order: 1,
    cover: FLOW_GIFS.storyboard,
    blocks: [
      { type: "h2", text: "1. 계정 만들기" },
      { type: "p", text: "xconda.ai에 접속해 계정을 만듭니다." },
      { type: "h2", text: "2. 크레딧 준비" },
      { type: "p", text: "크레딧 팩은 1회 결제 방식입니다. 처음이라면 Starter Pack V1($6.90 · 2,020 크레딧)으로 충분히 체험할 수 있습니다." },
      { type: "h2", text: "3. Director's Cut 열기" },
      { type: "ol", items: ["이미지 엔진 선택", "연도 · 장소 설정", "시나리오 작성", "감독 · 아트 스타일 선택", "생성"] },
      { type: "callout", icon: "💡", text: "처음에는 Ad Storyboard 템플릿으로 시작하면 구조를 빠르게 익힐 수 있습니다." },
    ],
  },
  {
    id: "guide-prompt",
    type: "guide",
    title: "좋은 시나리오 작성법",
    summary: "인물 · 장소 · 감정 흐름 · 카메라를 담으면 9컷의 완성도가 달라집니다.",
    category: "시나리오",
    date: daysAgo(8),
    tags: ["Prompt", "Director's Cut"],
    order: 2,
    blocks: [
      { type: "p", text: "XCONDA는 인과관계 기반 AI입니다. 사건의 원인과 결과가 드러나도록 쓰면 컷 간 흐름이 자연스러워집니다." },
      { type: "h3", text: "체크리스트" },
      { type: "todo", items: [
        { text: "인물의 이름을 명시했나요? (Art Director Pro 연결에 필요)", checked: true },
        { text: "시간 · 장소를 적었나요?", checked: true },
        { text: "감정 변화(시작 → 전환 → 결말)가 있나요?", checked: false },
        { text: "핵심 소품이나 의상을 명시했나요?", checked: false },
      ] },
      { type: "h3", text: "예시" },
      { type: "quote", text: "1998년 서울, 비 오는 밤. 민지는 폐업한 필름 현상소 앞에서 아버지의 낡은 카메라를 발견한다. 망설이다 셔터를 누르는 순간, 거리의 네온이 하나씩 켜진다." },
    ],
  },
  {
    id: "guide-character",
    type: "guide",
    title: "캐릭터 일관성 유지하기",
    summary: "Art Director Pro에서 얼굴 · 의상이 모든 컷에서 유지되도록 설정하는 방법.",
    category: "캐릭터",
    date: daysAgo(12),
    tags: ["Art Director Pro"],
    order: 3,
    tool: "Art Director Pro",
    blocks: [
      { type: "ol", items: ["시나리오에 캐릭터 이름 포함", "얼굴 사진 업로드", "Detect Face → 캐릭터 시트 생성", "생성 및 재생성"] },
      { type: "callout", icon: "⚠️", text: "캐릭터 시트가 없으면 생성을 시작할 수 없습니다." },
    ],
  },

  /* ================================= FAQ ================================= */
  { id: "faq-1", type: "faq", order: 1, title: "크레딧은 어떻게 충전하나요?", summary: "크레딧 팩(Starter V1 · V2, Pro V1 · V2, Master)을 1회 결제로 구매할 수 있습니다. 구독 플랜은 출시 예정입니다.", category: "크레딧", date: daysAgo(3), tags: [] },
  { id: "faq-2", type: "faq", order: 2, title: "생성에 실패하면 크레딧이 차감되나요?", summary: "시스템 오류로 생성이 실패한 경우 차감된 크레딧은 자동으로 복구됩니다. 복구되지 않았다면 문의해 주세요.", category: "크레딧", date: daysAgo(3), tags: [] },
  { id: "faq-3", type: "faq", order: 3, title: "마음에 안 드는 컷만 다시 만들 수 있나요?", summary: "네. Director's Cut에서 해당 컷의 프롬프트만 수정해 개별 재생성할 수 있습니다. 나머지 컷의 맥락은 유지됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-4", type: "faq", order: 4, title: "캐릭터 얼굴이 컷마다 달라져요.", summary: "Art Director Pro에서 시나리오에 캐릭터 이름을 넣고, 얼굴 사진 업로드 후 Detect Face로 캐릭터 시트를 만들어 주세요. 이름으로 얼굴이 연결됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-5", type: "faq", order: 5, title: "360 Turn Studio에서 오브젝트를 지우려면?", summary: "마스크 툴로 지울 영역을 칠하고, 프롬프트를 비워 둔 채 실행하면 자동으로 지워집니다. 프롬프트를 입력하면 새 오브젝트가 배치됩니다.", category: "사용법", date: daysAgo(3), tags: [] },
  { id: "faq-6", type: "faq", order: 6, title: "만든 결과물을 상업적으로 사용할 수 있나요?", summary: "이용약관의 범위 내에서 사용 가능합니다. 타인의 초상 · 저작물을 사용하는 경우 반드시 권리자의 동의가 필요합니다.", category: "정책", date: daysAgo(3), tags: [] },
];

export const SAMPLE_ENTRIES: Entry[] = BASE_SAMPLE_ENTRIES.map((entry) => ({
  ...entry,
  translations: SAMPLE_ENTRY_EN[entry.id] ? { en: SAMPLE_ENTRY_EN[entry.id] } : undefined,
}));
